### ISSUE TITLE
expand readme

### ISSUE THREAD

**Issue by benjyz** [officialcryptomaster/pydex#10]
"PyDEX is a python-based DEX which makes use of the 0x protocol."

this is too brief. can you please add some more context? thanks

**Comment by benjyz** [comment]
I assume its open-orderbook relay strategy?

https://0x.org/wiki#Open-Orderbook

**Comment by officialcryptomaster** [comment]
Yes, for now it will implement the SRA which is Open Orderbook. We do plan to make it Matching model at a later date but that may not be a public project... depends on funding...

**Comment by officialcryptomaster** [comment]
Update readme via commit 45c0fdefa88eb23610f3ba1d876c4325804aaf4c
