### ISSUE TITLE
dependency: eth-abi

### ISSUE THREAD

**Issue by benjyz** [officialcryptomaster/pydex#12]
`eth-tester 0.1.0b37 has requirement eth-abi<3.0.0,>=2.0.0b4, but you'll have eth-abi 1.3.0 which is incompatible.`

**Comment by benjyz** [comment]
eth-abi 2.0.0 not released yet. 
eth-tester is implicit from somewhere else

**Comment by officialcryptomaster** [comment]
Ah, I guess I should separate out the explicit dependencies from implicit ones somehow... this is annoying to have to deal with this every time :)

**Comment by benjyz** [comment]
not sure whats the best way to handle dependency tree. these are the web3 ones

https://github.com/0xProject/web3.py/blob/master/setup.py#L70

```
eth-abi>=2.0.0b5,<3.0.0",
 eth-account>=0.2.1,<0.4.0",
 eth-hash[pycryptodome]>=0.2.0,<1.0.0",
 eth-utils>=1.3.0,<2.0.0",
 ethpm>=0.1.4a12,<1.0.0",
```

**Comment by benjyz** [comment]
tried with `pip3 install git+git://github.com/benjyz/eth-abi` . have to fix some upstream issues looks like

**Comment by officialcryptomaster** [comment]
I think you should delete your pydex_env directory and reinstall using `source setup` and then `pip3 install -r dev_requirements.txt`. I don't have any issues...
