### ISSUE TITLE
venv install issue

### ISSUE THREAD

**Issue by benjyz** [officialcryptomaster/pydex#19]
likely my local issue

do I have to install requirements everytime I activate? somehow packages get lost

```
 PYTHONPATH=./src ./pydex_env/bin/pytest
-bash: ./pydex_env/bin/pytest: No such file or directory
```

```
PYTHONPATH=./src ./pydex_env/bin/pytest
-bash: ./pydex_env/bin/pytest: No such file or directory
pluggy.manager.PluginValidationError: Plugin 'pytest_ethereum' could not be loaded: (web3 4.8.2 (/usr/local/lib/python3.7/site-packages), Requirement.parse('web3[tester]==4.4.1'), {'ethpm'})!
```

**Comment by officialcryptomaster** [comment]
`venv` and `virtualenv` are two separate things... this [this](https://stackoverflow.com/questions/41573587/what-is-the-difference-between-venv-pyvenv-pyenv-virtualenv-virtualenvwrappe)

This project uses `virtualenv`

I think you problem is that you have not installed the dev_dependencies inside your virtual environment. Every time you want to use the virtual environment, you have to activate it using `source ./pydex_env/bin/activate` - that includes when you want to want to install them in the first place. Once you have installed them, you do not need to reinstall them, you just need to activate the environment.
